# Generated by Django 4.0.3 on 2022-06-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=89)),
                ('date', models.DateField()),
                ('religion', models.CharField(max_length=78)),
                ('city', models.CharField(max_length=67)),
                ('age', models.PositiveIntegerField()),
                ('physical_disability', models.CharField(max_length=120)),
                ('education', models.CharField(max_length=120)),
                ('occupation', models.CharField(max_length=120)),
                ('img', models.ImageField(upload_to='img/')),
                ('biodata', models.FileField(upload_to='doc/')),
            ],
        ),
    ]
